In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [48]:
from ase import Atoms
from ase.io import read
from ase.units import Bohr
from ase.io.espresso import write_espresso_in

In [12]:
df = pd.read_csv('bandgaps_filtered.dat', names=['file', 'ho','lu', 'Egap'], delimiter=" ")
df

                       file      ho       lu    Egap
0    ZnO-LDAU_9.50_7.50.out  8.4423  11.8754  3.4331
1   ZnO-LDAU_12.00_7.00.out  8.3509  11.7824  3.4315
2    ZnO-LDAU_7.50_8.00.out  8.5432  11.9629  3.4197
3    ZnO-LDAU_5.00_9.00.out  8.7009  12.1157  3.4148
4   ZnO-LDAU_11.50_7.00.out  8.3814  11.7889  3.4075
5    ZnO-LDAU_6.00_8.50.out  8.6365  12.0435  3.4070
6    ZnO-LDAU_9.00_7.50.out  8.4818  11.8825  3.4007
7    ZnO-LDAU_4.00_9.50.out  8.7889  12.1879  3.3990
8   ZnO-LDAU_11.00_7.00.out  8.4133  11.7955  3.3822
9    ZnO-LDAU_7.00_8.00.out  8.5925  11.9706  3.3781
10   ZnO-LDAU_8.50_7.50.out  8.5230  11.8898  3.3668
11   ZnO-LDAU_5.50_8.50.out  8.6956  12.0517  3.3561
12   ZnO-LDAU_4.50_9.00.out  8.7684  12.1243  3.3559
13  ZnO-LDAU_10.50_7.00.out  8.4465  11.8022  3.3557
14   ZnO-LDAU_6.50_8.00.out  8.6442  11.9786  3.3344
15   ZnO-LDAU_8.00_7.50.out  8.5662  11.8972  3.3310
16  ZnO-LDAU_10.00_7.00.out  8.4811  11.8090  3.3279
17   ZnO-LDAU_5.00_8.50.out  8.7576  12.0601  3.3025

In [37]:
get_atom_obj = lambda fname : read("hubbard_scans/outputs/"+ fname)
get_a = lambda fname : read("hubbard_scans/outputs/"+ fname).cell[0][0]
get_c = lambda fname : read("hubbard_scans/outputs/"+ fname).cell[2][2]

In [43]:
df['a'] = df['file'].apply(get_a)
df['c'] = df['file'].apply(get_c)
df['c/a'] = df['c'] / df['a']

In [45]:
df.sort_values('a')

,file,ho,lu,Egap,a,c,c/a
7,ZnO-LDAU_4.00_9.50.out,8.7889,12.1879,3.3990,3.148420,5.043287,1.601847
12,ZnO-LDAU_4.50_9.00.out,8.7684,12.1243,3.3559,3.151492,5.046286,1.601237
3,ZnO-LDAU_5.00_9.00.out,8.7009,12.1157,3.4148,3.152094,5.046596,1.601029
17,ZnO-LDAU_5.00_8.50.out,8.7576,12.0601,3.3025,3.154308,5.050189,1.601045
11,ZnO-LDAU_5.50_8.50.out,8.6956,12.0517,3.3561,3.154903,5.050483,1.600836
5,ZnO-LDAU_6.00_8.50.out,8.6365,12.0435,3.4070,3.155472,5.050813,1.600652
14,ZnO-LDAU_6.50_8.00.out,8.6442,11.9786,3.3344,3.158314,5.054831,1.600484
9,ZnO-LDAU_7.00_8.00.out,8.5925,11.9706,3.3781,3.158870,5.055127,1.600296
2,ZnO-LDAU_7.50_8.00.out,8.5432,11.9629,3.4197,3.159411,5.055421,1.600115
15,ZnO-LDAU_8.00_7.50.out,8.5662,11.8972,3.3310,3.162276,5.059571,1.599978
10,ZnO-LDAU_8.50_7.50.out,8.5230,11.8898,3.3668,3.162795,5.059864,1.599808
6,ZnO-LDAU_9.00_7.50.out,8.4818,11.8825,3.4007,3.163300,5.060154,1.599644
0,ZnO-LDAU_9.50_7.50.out,8.4423,11.8754,3.4331,3.163793,5.060443,1.599486
16,ZnO-LDAU_10.00_7.00.out,8.4811,11.8090,3.3279,3.166678,5.064731,1.599383
13,ZnO-LDAU_10.50_7.00.out,8.4465,11.8022,3.3557,3.167144,5.065031,1.599243
8,ZnO-LDAU_11.00_7.00.out,8.4133,11.7955,3.3822,3.167607,5.065318,1.599099
4,ZnO-LDAU_11.50_7.00.out,8.3814,11.7889,3.4075,3.168062,5.065597,1.598958
1,ZnO-LDAU_12.00_7.00.out,8.3509,11.7824,3.4315,3.168506,5.065878,1.598822

In [49]:
ZnO_Ud12_Up7 = df['file'].loc[1]

atoms: Atoms = get_atom_obj(ZnO_Ud12_Up7)

In [64]:
df.to_csv('dataframe.csv', index=False, sep=' ')

In [66]:
for v in atoms.cell:
    print(v)

[3.16850641 0.         0.        ]
[-1.5842532   2.74400704  0.        ]
[0.         0.         5.06587777]

In [68]:
atoms.get_scaled_positions()

array([[0.33333333, 0.66666667, 0.99920088],
       [0.66666667, 0.33333333, 0.49920088],
       [0.33333333, 0.66666667, 0.38079912],
       [0.66666667, 0.33333333, 0.88079912]])